name:                gtk-sni-tray
version:             0.1.14.0
github:              "IvanMalison/gtk-sni-tray"
license:             BSD3
author:              "Ivan Malison"
maintainer:          "IvanMalison@gmail.com"
copyright:           "2018 Ivan Malison"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            A standalone StatusNotifierItem/AppIndicator tray
category:            System

description:         Please see the README on Github at <https://github.com/IvanMalison/gtk-sni-tray#readme>

library:
  exposed-modules:
    - StatusNotifier.TransparentWindow
    - StatusNotifier.Tray
  dependencies:
    - base >= 4.7 && < 5
    - bytestring >= 0.10 && < 0.13
    - containers >= 0.5 && < 0.8
    - dbus >= 1 && < 2
    - dbus-menu >= 0.1.3.1 && < 0.2
    - directory >= 1.2 && < 1.4
    - enclosed-exceptions >= 1.0.0.1 && < 1.1
    - filepath >= 1.3 && < 1.6
    - gi-cairo >= 1.0 && < 1.1
    - gi-cairo-render >= 0.1 && < 0.2
    - gi-cairo-connector >= 0.1 && < 0.2
    - gi-dbusmenugtk3 >= 0.4 && < 0.5
    - gi-gdk3 >= 3.0 && < 3.1
    - gi-gdkpixbuf >= 2.0.16 && < 2.1
    - gi-glib >= 2.0 && < 2.1
    - gi-gtk3 >= 3.0 && < 3.1
    - gtk-strut >= 0.1.4 && < 0.2
    - haskell-gi >= 0.21.2 && < 0.27
    - haskell-gi-base >= 0.21.1 && < 0.27
    - hslogger >= 1.2 && < 1.4
    - status-notifier-item >= 0.3.2 && < 0.4
    - text >= 1.2 && < 2.2
    - transformers >= 0.4 && < 0.7
    - transformers-base >= 0.4 && < 0.5
    - unix >= 2.7 && < 2.9
  source-dirs: src
  pkg-config-dependencies:
    - gtk+-3.0

executables:
  gtk-sni-tray-standalone:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - dbus
      - dbus-hslogger >= 0.1.0.1 && < 0.2
      - containers
      - gi-gdk3
      - gi-gtk3
      - gi-gtk-layer-shell >= 0.1 && < 0.2
      - gtk-sni-tray
      - gtk-strut
      - hslogger
      - optparse-applicative >= 0.14 && < 0.19
      - status-notifier-item
      - text
      - unix
