name:                gtk-sni-tray
version:             0.1.10.2
github:              "IvanMalison/gtk-sni-tray"
license:             BSD3
author:              "Ivan Malison"
maintainer:          "IvanMalison@gmail.com"
copyright:           "2018 Ivan Malison"

extra-source-files:
- README.md
- ChangeLog.md
- dbus-xml/com.canonical.dbusmenu.xml

synopsis:            A standalone StatusNotifierItem/AppIndicator tray
category:            System

description:         Please see the README on Github at <https://github.com/IvanMalison/gtk-sni-tray#readme>

library:
  exposed-modules:
    - StatusNotifier.TransparentWindow
    - StatusNotifier.Tray
  other-modules:
    - StatusNotifier.DBusMenu
    - StatusNotifier.DBus.Client.Util
    - StatusNotifier.DBus.Client.DBusMenu
  dependencies:
    - base >= 4.7 && < 5
    - bytestring
    - containers
    - dbus >= 1.0.0 && < 2.0.0
    - directory
    - enclosed-exceptions >= 1.0.0.1
    - filepath
    - gi-cairo
    - gi-cairo-render
    - gi-cairo-connector
    - gi-gdk3
    - gi-gdkpixbuf >= 2.0.16
    - gi-glib
    - gi-gtk3
    - gtk-strut >= 0.1.4.0
    - haskell-gi >= 0.21.2
    - haskell-gi-base >= 0.21.1
    - hslogger
    - status-notifier-item >= 0.3.2.0 && < 0.4.0.0
    - text
    - template-haskell
    - transformers
    - transformers-base >= 0.4
    - unix
  source-dirs: src
  pkg-config-dependencies:
    - gtk+-3.0

executables:
  gtk-sni-tray-standalone:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - dbus
      - dbus-hslogger >= 0.1.0.1 && < 0.2.0.0
      - containers
      - gi-gdk3
      - gi-gtk3
      - gi-gtk-layer-shell
      - gtk-sni-tray
      - gtk-strut
      - hslogger
      - optparse-applicative
      - status-notifier-item
      - text
      - unix
